### PR TITLE
[Fix] Dockerfiles

### PR DESCRIPTION
**Pull request by yosh1**

### CODE REVIEW

**Review by tenmakamatani — APPROVED** [review]
approve

**Comment by yosh1** [comment]
Why did you approve?

**Comment by yosh1** [comment]
This didn't must be approved.

**Comment by tenmakamatani** [comment]
I don't know about Docker very much.

**Comment by yosh1** [comment]
Your English is broken...
I don't understand your one...

**Comment by tenmakamatani** [comment]
I want to speak Japanese.

**Comment by yosh1** [comment]
I see.
You are able to speak Japanese, but You must write English as usual!

**Comment by yosh1** [comment]
Oops, I'm tired to write English..XD

**Comment by yosh1** [comment]
OK, you are able to merge this Pull Request.
Thank you for talking w/ me!

**Comment by tenmakamatani** [comment]
OKOK

**Pull request merged**
